stages:
  - build_frontend
  - build_backend
  - test
  - publish
  - deploy

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  CONTAINER_NAME: "se2springbreak-app"
  BUILD_ARTIFACTS_DIR: "artifacts"
  DOCKER_TLS_CERTDIR: ""

frontend:
  stage: build_frontend
  image: openjdk:17-jdk-slim-buster
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew frontend:build --stacktrace
  cache:
    key: "$CI_COMMIT_SHA"
    policy: pull-push
    paths:
      - frontend/build
      - .gradle
  artifacts:
    paths:
      - frontend/build/distributions/*

backend:
  stage: build_backend
  image: openjdk:17-jdk-slim-buster
  dependencies:
    - frontend
  before_script:
    - chmod +x ./gradlew
    - rm -rf backend/src/main/resources/static/
    - cp -r frontend/build/distributions backend/src/main/resources/static
  script:
    - ./gradlew backend:build -x test --stacktrace
  cache:
    key: "$CI_COMMIT_SHA"
    policy: pull-push
    paths:
      - backend/build
      - .gradle
  artifacts:
    paths:
      - backend/build/libs/*.jar

publish:
  stage: publish
  image: docker:latest
  dependencies:
    - backend
  services:
    - name: docker:dind
      command: ["--tls=false"]
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_USER/$TAG_COMMIT"
    - docker push "$CI_REGISTRY_USER/$TAG_LATEST"

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
      - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
      - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CONTAINER_NAME || true"
      - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8080:8080 --name my-app $TAG_COMMIT"
  environment:
    name: production
    url: http://cloud.jgdperl.com:8080